### ISSUE TITLE
[TASK] Extend identity sdk for Rate-limited forum posting use case

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/semaphore-anchor#5]
### Task Checklist 

- [ ]  Implementing a RateLimiting circuit
- [ ]  Integrate RateLimiting circuit into contracts
- [ ]  Add Typescript implementation of Rate-limited forum posting

**Comment by semaraugusto** [comment]
# Overview

Should integrate our multi-chain semaphore with: Rate Limiting Nullifier (https://ethresear.ch/t/semaphore-rln-rate-limiting-nullifier-for-spam-prevention-in-anonymous-p2p-setting/5009)

## Relevant links:
* https://github.com/privacy-scaling-explorations/rln
* https://hackmd.io/7GR5Vi28Rz2EpEmLK0E0Aw
